# Generated by Django 4.1.1 on 2022-10-11 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('building_number', models.IntegerField()),
                ('housename', models.CharField(max_length=200)),
                ('pincode', models.IntegerField()),
                ('username_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
