# Generated by Django 4.1.1 on 2022-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_referrel'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrel',
            name='referredto',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
