# Generated by Django 4.1.1 on 2022-10-29 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_offers_additionalimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sellingprice',
            field=models.IntegerField(default=0),
        ),
    ]
