# Generated by Django 4.1.1 on 2022-10-28 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0002_offers_additionalimage'),
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObtainedOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalpricereducted', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.offers')),
            ],
        ),
    ]
