# Generated by Django 4.1.1 on 2022-10-28 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('store', '0002_offers_additionalimage'),
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserObtainedOffer1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offerpricereduced', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.offers')),
            ],
        ),
    ]
